# Generated by Django 6.0.3 on 2026-05-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0002_alter_diagnoza_options_alter_magazyn_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dostawca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                ("nip", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=100)),
                ("telefon", models.CharField(blank=True, max_length=20)),
                ("adres", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "verbose_name": "Dostawca",
                "verbose_name_plural": "Dostawcy",
            },
        ),
        migrations.CreateModel(
            name="KategoriaCzesci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                ("opis", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Kategoria części",
                "verbose_name_plural": "Kategorie części",
            },
        ),
        migrations.CreateModel(
            name="ProducentRoweru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                ("kraj", models.CharField(blank=True, max_length=50)),
                ("strona_www", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Producent roweru",
                "verbose_name_plural": "Producenci rowerów",
            },
        ),
        migrations.CreateModel(
            name="StanowiskoSerwisowe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=50)),
                ("opis", models.TextField(blank=True)),
                ("czy_aktywne", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Stanowisko serwisowe",
                "verbose_name_plural": "Stanowiska serwisowe",
            },
        ),
        migrations.CreateModel(
            name="TypRoweru",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=50)),
                ("opis", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Typ roweru",
                "verbose_name_plural": "Typy rowerów",
            },
        ),
        migrations.CreateModel(
            name="UslugaSerwisowa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nazwa", models.CharField(max_length=100)),
                ("opis", models.TextField(blank=True)),
                ("cena", models.DecimalField(decimal_places=2, max_digits=10)),
                ("czas_szacowany_minuty", models.PositiveIntegerField(default=30)),
            ],
            options={
                "verbose_name": "Usługa serwisowa",
                "verbose_name_plural": "Usługi serwisowe",
            },
        ),
        migrations.AddField(
            model_name="platnosc",
            name="metoda_platnosci",
            field=models.CharField(default="gotowka", max_length=30),
        ),
        migrations.AlterField(
            model_name="czesc",
            name="stan_magazynowy",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="czesc",
            name="stan_minimalny",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="rower",
            name="numer_seryjny",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="uzytkownik",
            name="rola",
            field=models.CharField(
                choices=[
                    ("klient", "Klient"),
                    ("mechanik", "Mechanik"),
                    ("magazynier", "Magazynier"),
                    ("admin", "Admin"),
                ],
                default="klient",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Adres",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ulica", models.CharField(max_length=100)),
                ("numer_budynku", models.CharField(max_length=10)),
                ("numer_lokalu", models.CharField(blank=True, max_length=10)),
                ("kod_pocztowy", models.CharField(max_length=10)),
                ("miasto", models.CharField(max_length=50)),
                (
                    "uzytkownik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adresy",
                        to="mainapp.uzytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Adres",
                "verbose_name_plural": "Adresy",
            },
        ),
        migrations.CreateModel(
            name="HistoriaStatusu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=30)),
                ("data_zmiany", models.DateTimeField(auto_now_add=True)),
                ("komentarz", models.TextField(blank=True)),
                (
                    "zlecenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historia_statusow",
                        to="mainapp.zlecenieserwisowe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historia statusu",
                "verbose_name_plural": "Historie statusów",
            },
        ),
        migrations.AddField(
            model_name="czesc",
            name="kategoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="czesci",
                to="mainapp.kategoriaczesci",
            ),
        ),
        migrations.CreateModel(
            name="Kontakt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefon", models.CharField(max_length=20)),
                ("dodatkowy_email", models.EmailField(blank=True, max_length=100)),
                (
                    "preferowany_kontakt",
                    models.CharField(
                        choices=[("telefon", "Telefon"), ("email", "E-mail")],
                        default="telefon",
                        max_length=20,
                    ),
                ),
                (
                    "uzytkownik",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kontakty",
                        to="mainapp.uzytkownik",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontakt",
                "verbose_name_plural": "Kontakty",
            },
        ),
        migrations.CreateModel(
            name="NotatkaSerwisowa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tresc", models.TextField()),
                ("data_dodania", models.DateTimeField(auto_now_add=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notatki_serwisowe",
                        to="mainapp.uzytkownik",
                    ),
                ),
                (
                    "zlecenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notatki",
                        to="mainapp.zlecenieserwisowe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notatka serwisowa",
                "verbose_name_plural": "Notatki serwisowe",
            },
        ),
        migrations.AddField(
            model_name="rower",
            name="producent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rowery",
                to="mainapp.producentroweru",
            ),
        ),
        migrations.CreateModel(
            name="TerminSerwisu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_terminu", models.DateTimeField()),
                ("opis", models.TextField(blank=True)),
                (
                    "stanowisko",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="terminy",
                        to="mainapp.stanowiskoserwisowe",
                    ),
                ),
                (
                    "zlecenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terminy",
                        to="mainapp.zlecenieserwisowe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Termin serwisu",
                "verbose_name_plural": "Terminy serwisu",
            },
        ),
        migrations.AddField(
            model_name="rower",
            name="typ_roweru",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rowery",
                to="mainapp.typroweru",
            ),
        ),
        migrations.CreateModel(
            name="WykonanaUsluga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ilosc", models.PositiveIntegerField(default=1)),
                (
                    "cena_wykonania",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "usluga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wykonania",
                        to="mainapp.uslugaserwisowa",
                    ),
                ),
                (
                    "zlecenie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wykonane_uslugi",
                        to="mainapp.zlecenieserwisowe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wykonana usługa",
                "verbose_name_plural": "Wykonane usługi",
            },
        ),
        migrations.CreateModel(
            name="ZamowienieCzesci",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_zamowienia", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nowe", "Nowe"),
                            ("zamowione", "Zamówione"),
                            ("dostarczone", "Dostarczone"),
                            ("anulowane", "Anulowane"),
                        ],
                        default="nowe",
                        max_length=30,
                    ),
                ),
                ("uwagi", models.TextField(blank=True)),
                (
                    "dostawca",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zamowienia",
                        to="mainapp.dostawca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zamówienie części",
                "verbose_name_plural": "Zamówienia części",
            },
        ),
        migrations.CreateModel(
            name="PozycjaZamowienia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ilosc", models.PositiveIntegerField()),
                (
                    "cena_jednostkowa",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "czesc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pozycje_zamowien",
                        to="mainapp.czesc",
                    ),
                ),
                (
                    "zamowienie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pozycje",
                        to="mainapp.zamowienieczesci",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pozycja zamówienia",
                "verbose_name_plural": "Pozycje zamówień",
            },
        ),
    ]
