# Generated by Django 6.0.3 on 2026-05-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0003_dostawca_kategoriaczesci_producentroweru_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zlecenieserwisowe",
            name="status",
            field=models.CharField(
                choices=[
                    ("nowe", "Nowe"),
                    ("w_realizacji", "W realizacji"),
                    ("diagnoza", "Diagnoza"),
                    ("naprawa", "Naprawa"),
                    ("gotowe", "Gotowe do odbioru"),
                    ("zakonczone", "Zakończone"),
                    ("anulowane", "Anulowane"),
                ],
                default="nowe",
                max_length=30,
            ),
        ),
    ]
