# Generated by Django 6.0.3 on 2026-05-28 14:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0004_alter_zlecenieserwisowe_status"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION oblicz_koszt_czesci(p_zlecenie_id BIGINT)
            RETURNS NUMERIC AS $$
            DECLARE
                v_koszt NUMERIC;
            BEGIN
                SELECT COALESCE(SUM(zc.ilosc * c.cena), 0)
                INTO v_koszt
                FROM mainapp_zuzytaczesc zc
                JOIN mainapp_czesc c ON c.id = zc.czesc_id
                WHERE zc.zlecenie_id = p_zlecenie_id;

                RETURN v_koszt;
            END;
            $$ LANGUAGE plpgsql;


            CREATE OR REPLACE PROCEDURE zmien_status_zlecenia_sql(
                p_zlecenie_id BIGINT,
                p_nowy_status VARCHAR,
                p_komentarz TEXT DEFAULT ''
            )
            LANGUAGE plpgsql
            AS $$
            BEGIN
                UPDATE mainapp_zlecenieserwisowe
                SET status = p_nowy_status
                WHERE id = p_zlecenie_id;

                IF NOT FOUND THEN
                    RAISE EXCEPTION 'Nie znaleziono zlecenia o ID %', p_zlecenie_id;
                END IF;

                INSERT INTO mainapp_historiastatusu (
                    zlecenie_id,
                    status,
                    komentarz,
                    data_zmiany
                )
                VALUES (
                    p_zlecenie_id,
                    p_nowy_status,
                    COALESCE(p_komentarz, ''),
                    NOW()
                );
            END;
            $$;


            CREATE OR REPLACE FUNCTION ustaw_date_zakonczenia_zlecenia()
            RETURNS TRIGGER AS $$
            BEGIN
                IF NEW.status IN ('gotowe', 'zakonczone', 'zakończone')
                   AND OLD.status IS DISTINCT FROM NEW.status
                   AND NEW.data_zakonczenia IS NULL THEN
                    NEW.data_zakonczenia = NOW();
                END IF;

                RETURN NEW;
            END;
            $$ LANGUAGE plpgsql;


            DROP TRIGGER IF EXISTS trg_ustaw_date_zakonczenia_zlecenia
            ON mainapp_zlecenieserwisowe;

            CREATE TRIGGER trg_ustaw_date_zakonczenia_zlecenia
            BEFORE UPDATE OF status
            ON mainapp_zlecenieserwisowe
            FOR EACH ROW
            EXECUTE FUNCTION ustaw_date_zakonczenia_zlecenia();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS trg_ustaw_date_zakonczenia_zlecenia
            ON mainapp_zlecenieserwisowe;

            DROP FUNCTION IF EXISTS ustaw_date_zakonczenia_zlecenia();

            DROP PROCEDURE IF EXISTS zmien_status_zlecenia_sql(BIGINT, VARCHAR, TEXT);

            DROP FUNCTION IF EXISTS oblicz_koszt_czesci(BIGINT);
            """
        ),
    ]
